routes/web.php
        Route::post('/wx/read','Auth\LoginWinxinController@readWxInfo')->name('wx.read');
        Route::get('/wx/login','Auth\LoginWinxinController@login')->name('wx.login');

        /**
         * 忘记密码
         */
        Route::get('/forget','Auth\ForgetController@forget')->name('forget');
        # 获取第一步验证码
        Route::post('/forget/account','Auth\ForgetController@account')->name('forget.account');
        # 第二步：进入填写密码
        Route::get('/forget_too/{key?}','Auth\ForgetController@forget_too')->name('forget_too');
        # 处理第二步：
        Route::post('/forget/store_pwd','Auth\ForgetController@store_pwd')->name('forget.store_pwd');
        # 处理第一步验证码字段相关
        Route::post('/forget','Auth\ForgetController@store')->name('forget.store');
    });

    # 测试相关模块
    Route::get('/test/sub','TestController@sub')->name('sub');
    Route::get('/test/form','TestController@form')->name('test.form');
    Route::get('/test/store','TestController@store')->name('test.store');
    Route::get('/test/qcode','TestController@qcode')->name('qcode');
    Route::get('/test/show','TestController@show')->name('qcode.show');
    Route::get('/test/qcodeStore','TestController@qcodeStore')->name('qcodeStore');
    /**
     *
     * 注册注销相关
     */
    # 注册
    Route::get('/register','Auth\RegisterController@register')->name('register');
    # 注册处理
    Route::post('/register','Auth\RegisterController@store')->name('register.store');
    # 获取验证码
    Route::post('/register/account','Auth\RegisterController@account')->name('register.account');
    #
    Route::get('/register/verify','Auth\RegisterController@verify')->name('verify');

    Route::post('/logout','Auth\LoginController@logout')->name('logout');

    Route::post('/subscriber','SubscriberController@store')->name('subscriber');






    # 必须登录的情况下使用
    Route::middleware(['auth'])->group(function (){
        # 注销
        Route::post('/logout','Auth\LoginController@logout')->name('logout');

        # 收藏清单
        Route::get('/wish','WishController@list')->name('wish');

        # 删除收藏
        Route::delete('/wish','WishController@delete')->name('wish.delete');
        Route::post('/wish','WishController@add')->name('wish.add');


        # 购物车
        Route::get('/carts','CartController@list')->name('cart');
        Route::delete('/carts','CartController@delete')->name('cart.delete');
        Route::put('/carts','CartController@create')->name('cart.create');


        # 订单信息
        Route::get('/order', 'OrderController@list')->name('order.list');
        Route::get('/order/{id}', 'OrderController@show')->name('order.show');
        Route::post('/order/create', 'OrderController@create')->name('order.create');
        Route::post('/order/refund', 'OrderController@refund')->name('order.refund');


        Route::get('/alipay/return','PayController@alipayReturn')->name('pay.alipay.return'); # 前端回调页面
        Route::get('/alipay/{id}','PayController@payByAlipay')->name('pay.alipay');

        Route::get('/wechat/{id}','PayController@payByWechat')->name('pay.wechat');

        # 个人资料页面
        Route::get('/me', 'MeController@index')->name('me.index');


        # 收货地址
        Route::get('/me/address', 'MeController@address')->name('me.address');
        Route::get('/me/address/add_edit/{id?}', 'MeController@add_edit')->name('me.address.add_edit');
        Route::delete('/me/address/delete', 'MeController@delete')->name('me.address.delete');

        # 处理收货地址
        Route::post('/me/address', 'MeController@create')->name('me.address.create');
        Route::put('/me/address', 'MeController@update')->name('me.address.update');

    });


    Route::post('/alipay/notify','PayController@alipayNotify')->name('pay.alipay.notify'); # 支付宝支付成功服务端回调页面

    Route::post('/wechat/notify','PayController@wechatNotify')->name('pay.wechat.notify'); # 微信支付成功服务端回调页面

    Route::post('/wechat/refund/notify','PayController@wechatRefundNotify')->name('pay.wechat.refund'); # 微信退款服务端回调页面


    /**
     * 杂项
     * 关于公司情况的一些模块
     */
    Route::get('/trems_conditions','About\AboutController@trems_conditions');

    # 分类模块
    Route::get('/category','CategoryController@index')->name('category');
    Route::get('/category/{id}','CategoryController@show')->name('category.show');

    # 商品模块
    Route::get('/product/{id}','ProductController@show')->name('product.show');
    Route::get('/product','ProductController@list')->name('product.list');


    Route::namespace('Admin')->group(function () {
        Route::name('admin.')->prefix('admin')->group(function (){

            // 必须登录状态下才能进入
            Route::group(['middleware' => ['auth.admin']], function () {


                Route::get('/', 'IndexController@index')->name('index');
                // 权限控制路由
                Route::group(['middleware'=>'admin.permission'],function (){
                    Route::get('/welcome', 'IndexController@welcome')->name('welcome');;

                    /**
                     * 角色相关
                     */
                    Route::get('/admins/role/store/{id?}', 'AdminController@roleEditOrAdd')->name('admins.role.edit_or_add');
                    Route::get('/admins/role', 'AdminController@role')->name('admins.role');
                    Route::post('/admins/role/store', 'AdminController@roleStore')->name('admins.role.store');
                    Route::delete('/admins/role','AdminController@roleDelete')->name('admins.role.delete');

                    /**
                     * 权限相关
                     */
                    Route::get('/admins/permission', 'AdminController@permission')->name('admins.permission');
                    Route::get('/admins/permission/store/{id?}', 'AdminController@permissionEditOrAdd')->name('admins.permission.edit_or_add');
                    Route::post('/admins/permission/store', 'AdminController@permissionStore')->name('admins.permission.store');
                    Route::get('/admins/permission', 'AdminController@permission')->name('admins.permission');
                    Route::delete('/admins/permission','AdminController@permissionDelete')->name('admins.permission.delete');


                    /**
                     * 管理员管理
                     */
                    Route::get('/admins', 'AdminController@admins')->name('admins.admins');
                    Route::get('/admins/store/{id?}', 'AdminController@adminsEditOrAdd')->name('admins.edit_or_add');
                    Route::post('/admins/store', 'AdminController@adminsStore')->name('admins.store');
                    Route::get('/admins', 'AdminController@admins')->name('admins');
                    Route::delete('/admins','AdminController@adminsDelete')->name('admins.delete');
                    Route::put('/admins/active','AdminController@adminsActived')->name('admins.active');

                    /**
                     * 用户管理
                     */
                    Route::get('/users', 'UserController@list')->name('admins.users');
                    Route::get('/users/store/{id?}', 'UserController@addOrEdit')->name('user.add_or_edit');
                    Route::put('/users/store/{id}', 'UserController@update')->name('user.update');
                    Route::post('/users/store', 'UserController@create')->name('user.create');
                    Route::delete('/users','UserController@delete')->name('user.delete');

                    /**
                     * 分类管理
                     */
                    Route::get('/category', 'CategoryController@list')->name('category');
                    Route::get('/category/store/{id?}', 'CategoryController@addOrEdit')->name('category.add_or_edit');
                    Route::put('/category/store', 'CategoryController@update')->name('category.update');
                    Route::post('/category/store', 'CategoryController@create')->name('category.create');
                    Route::delete('/category','CategoryController@delete')->name('category.delete');

                    /**
                     * 商品管理
                     */
                    Route::get('/product', 'ProductController@list')->name('product');
                    Route::get('/product/store/{id?}', 'ProductController@addOrEdit')->name('product.add_or_edit');
                    Route::put('/product/store', 'ProductController@update')->name('product.update');
                    Route::post('/product/store', 'ProductController@create')->name('product.create');
                    Route::delete('/product','ProductController@delete')->name('product.delete');
                    Route::post('/upload/product','ProductController@upload')->name('product.upload');

                    /**
                     * 首页头图管理
                     */
                    Route::get('/banner', 'BannerController@list')->name('banner');
                    Route::get('/banner/store/{id?}', 'BannerController@add')->name('banner.add');
                    Route::post('/banner/store', 'BannerController@create')->name('banner.create');
                    Route::delete('/banner','BannerController@delete')->name('banner.delete');


                    /**
                     * 订单模块管理
                     */
                    Route::get('/order', 'OrderController@list')->name('order');
                    Route::get('/order/{id}', 'OrderController@show')->name('order.show');
                    Route::post('/order/ship', 'OrderController@ship')->name('order.ship');
                    Route::post('/order/refund', 'OrderController@refund')->name('order.refund'); # 退款
//                    Route::post('/product/store', 'ProductController@create')->name('product.create');


                    Route::get('/express', 'ExpressController@import')->name('import');


                });
            });

            Route::get('/login','LoginController@login')->name('login');
            Route::post('/login','LoginController@store')->name('store');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;
use App\Http\Traits\ProductCacheTrait;
use App\Scope\ProductScope;

class Product extends Model
{

    use ProductCacheTrait;

    public $guarded = [];

    const total = 10;

    const type = 'DESC';

    const key = 'product_list';

    const latest = 'product_latest';

    const simpleKey = 'simple_key_';

    const len = 9;

    public $hidden = [
        'updated_at'
        ,'actived'
        ,'cName'
    ];

    public $appends = [
        'image_src'
    ];

    public static function boot()
    {
        parent::boot();

        static::addGlobalScope(new ProductScope);
    }
    /**
     * 获取所有的商品数据
     * @param bool $page true = 分页数据获取 false = 获取全部数据
     * @return Product[]|\Illuminate\Contracts\Pagination\LengthAwarePaginator|Collection|mixed|string|void
     */
    public static function getProductsAll($page=true)
    {
        if( $page ) {
            $products = self::getPageProduct();
        }else{
            $products = self::getAllProduct();
        }
        return $products;
    }

    /**
     * 后台管理模块
     * 分页数据获取商品数据
     * @return \Illuminate\Contracts\Pagination\LengthAwarePaginator
     */
    public static function getPageProduct()
    {
        $products = self::withoutGlobalScope(ProductScope::class)->with(['productSkus','category','comments.user'])->orderBy('created_at',self::type)
                    ->paginate(self::total);

        return $products;
    }

    /**
     * 获取所有的商品
     * @return Product[]|Collection|mixed|string|void
     */
    public static function getAllProduct()
    {
        $products = self::withoutGlobalScope(ProductScope::class)->get();
        return $products;
    }

    public static function getSimpleProduct($pid)
    {
        $product = self::simpleByCacheProduct($pid);
        return $product;
    }
    /**
     * 关联图片
     * 一对一
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function image()
    {
        return $this->hasOne(Image::class,'product_id','id')->select('id','src','product_id');
    }

    /**
     * 关联分类
     * 多对一
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Category::class,'category_id','id')->select('id','name');
    }

    /**
     * 关联sku
     * 一对多
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function productSkus()
    {
        return $this->hasMany(ProductSku::class,'product_id','id');
    }

    /**
     * 关联评论
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class, 'product_id','id');
    }

    /**
     * 推荐的列表
     * 算法：
     * 分类优先
     * 销量优先
     * 评论优先
     * 价格优先
     */
    public static function getGoodsProductOnCategory($cid,$pid)
    {
        $products = Category::getCategoryByProduct($cid);

        $products = $products->where('category_id',$cid)->whereNotIn('id',$pid)->sortByDesc('sold_count')->take(10);

        $products->shuffle();

        return $products;
    }
    /**
     * 修改器
     * @return int
     */
    public function getStockAttribute()
    {
        $stock = 0;
        foreach ($this->productSkus as $sku){
            $stock += $sku->stock;
        }
        return $stock;
    }

    public function getRatingXingAttribute()
    {
        $value = $this->rating;
        $value= max(1,sprintf('%d',$value));
        return str_repeat('⭐',$value);
    }

    public function getSku1Attribute()
    {
        return $this->productSkus->first();
    }

    public function getSku2Attribute()
    {
        return $this->productSkus->last();
    }

    public function getProductImgAttribute()
    {
        return $this->image->src;
    }

    public function getStrPriceAttribute()
    {
        return '￥' . $this->price;
    }

    /**
     * 数据排序
     * @param $products
     * @param $sort
     * @return mixed
     */
    public function productSort($products,$sort)
    {
        switch ($sort){
            case 'sale':
                return $products->sortByDesc('sold_count');
                break;
            case 'review':
                return $products->sortByDesc('review_count');
                break;
            case 'h_price':
                return $products->sortByDesc('price');
                break;
            case 'b_price':
                return $products->sortBy('price');
                break;
            default:
                return $products->sortByDesc('created_at');
                break;
        }
    }

    // 分类数据组装
    public function productPage($products,$currentPage)
    {
        $pageSize = 6;  #每页多少数据
        $total = $products->count(); # 总数量
        $endPage = (int)ceil($total/$pageSize);
        $nextPage = (int)$currentPage+1;
        $prevPage = (int)$currentPage-1;


        if( $currentPage >= $endPage ){
            $currentPage = $endPage;
            $nextPage = $endPage;
        }
        if( $currentPage <= 1 ){
            $currentPage = 1;
            $prevPage = 1;
        }

        # 从当前页*5取出指定条数
        $products = $products->slice(($currentPage-1)*$pageSize);
        $products = $products->take($pageSize);

        return [
            'products' => $products,
            'next' => $nextPage,
            'prev' => (int)$prevPage,
            'endPage' => $endPage,
            'current' => $currentPage
        ];
    }

    /**
     * 获取商品的最近信息 （5条）
     */
    public static function getSubscription($len=5)
    {
        $products = self::query()->orderBy('created_at','DESC')->limit(5)->get();
        return $products;
    }

    public function getCNameAttribute()
    {
        if(!$cate = $this->category) {
            $cname = '其他';
        }else{
            $cname = $cate->name;
        }
        return str_limit($cname,4,'...');
    }


    public function getImageSrcAttribute()
    {
        return $this->image->src ?? '/404.jpg';
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Product;
use App\Models\Banner;

class ProductController extends Controller
{
    public function show(Request $request)
    {
        $pid = $request->id;
        if( !$pid || !$product = Product::getSimpleProduct($pid) ) {
            return view('error.404',['msg'=>'商品不存在']);
        }

        $cid = $product->category->id;

        # 推荐
        $goods = Product::getGoodsProductOnCategory($cid,$pid)->take(4);

        return view('product.simple',compact('product','goods'));
    }

    public function list(Request $request,Product $product)
    {
        $products = Product::getProductsAll(false);

        $sort = $request->sort ?? 'new';

        $products = $product->productSort($products,$sort);

        $currentPage = $request->current ?? 1;

        # 分页数据组装
        $result = $product->productPage($products,$currentPage);

        $products = $result['products'];

        return view('product.show',compact('products','sort','result'));
    }
}

resources/views/admin/product/add_edit.blade.php
@extends('admin.common.layout')
@section('body')
    
    <body>
        <div class="x-body">

            @if($id)
                <form class="layui-form layui-form-pane" action="{{ route('admin.product.update',['id' => $id]) }}" method="post">
                    @method('put')
            @else
                <form class="layui-form layui-form-pane" action="{{ route('admin.product.create') }}" method="post">
                    @method('post')
            @endif
                @csrf

                 @if( $status = session('status') )
                     <button class="layui-btn layui-btn-danger layui-btn-radius">{{ $status }}</button>
                 @endif
                    @if ($errors->any())
                        @foreach ($errors->all() as $error)
                            <button class="layui-btn layui-btn-danger layui-btn-radius">{{ $error }}</button>
                        @endforeach
                    @endif
                <div class="layui-form-item">
                    <label class="layui-form-label">商品名称</label>
                    <div class="layui-input-block">
                        <input required type="text" name="name"  value="{{ old('name') ?? $product->name ?? ''}}" autocomplete="off" placeholder="商品名称" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <div class="layui-form-item">
                        <img id="product_img" style="max-width: 400px; max-height: 600px" src="{{ old('product_img') ?? $product->product_img ?? '' }}" alt="">
                        <input required type="hidden" id="product" name="product_img" value="{{ old('product_img') ?? $product->product_img ?? '' }}">
                    </div>
                        <input type="file" name="file" class="layui-upload-file product">
                </div>

                <div class="layui-form-item">
                    <label class="layui-form-label">分类选择</label>
                    <div class="layui-input-block">
                        <select required name="category" lay-filter="aihao">
                            @foreach($categoies as $categoy)
                                <option value="{{ $categoy->id }}" @if( ( old('category') ?? $product->category_id ?? '') == $categoy->id  ) selected @endif>{{ $categoy->name ?? '' }}</option>
                            @endforeach
                        </select><div class="layui-unselect layui-form-select"><div class="layui-select-title"><input type="text" placeholder="请选择" value="阅读" readonly="" class="layui-input layui-unselect"><i class="layui-edge"></i></div><dl class="layui-anim layui-anim-upbit"><dd lay-value="" class="layui-select-tips">请选择</dd><dd lay-value="0" class="">写作</dd><dd lay-value="1" class="layui-this">阅读</dd><dd lay-value="2" class="">游戏</dd><dd lay-value="3" class="">音乐</dd><dd lay-value="4" class="">旅行</dd></dl></div>
                    </div>
                </div>

                <div class="layui-form-item reday-insert" pane="">
                    <label class="layui-form-label">是否上架</label>
                    <div class="layui-input-block">
                        @if( old('actived') ?? $product->actived ?? '' )
                            <input type="radio" name="actived" value="1" title="上架" checked>
                            <input type="radio" name="actived" value="0" title="下架">
                        @else
                            <input type="radio" name="actived" value="1" title="上架">
                            <input type="radio" name="actived" value="0" title="下架" checked>
                        @endif
                    </div>
                </div>

                <div class="layui-form-item layui-form-text">
                    <label class="layui-form-label">商品详情</label>
                    <div class="layui-input-block">
                        <textarea name="description" id="demo" placeholder="请输入内容" class="layui-textarea">{{ old('description') ??  $product->description ?? ''  }}</textarea>
                    </div>
                </div>

                    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 50px;">
                        <legend>SKU1</legend>
                    </fieldset>
                    <div class="layui-form-item">
                        <label class="layui-form-label">Sku名称</label>
                        <div class="layui-input-block">
                            <input required type="text" name="skus[new1][name]" value="{{ old('skus.new1.name') ?? $product->sku1->name ?? '' }}" autocomplete="off" placeholder="Sku名称" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <div class="layui-form-item">
                            <img id="product_img" style="max-width: 400px; max-height: 600px" src="{{ old('skus.new1.skuImg')  ?? $product->sku1->image->src ?? '' }}" alt="">
                            <input required type="hidden" id="product" name="skus[new1][skuImg]" value="{{ old('skus.new1.skuImg') ?? $product->sku1->image->src ?? '' }}">
                        </div>
                        <input type="file" name="file" class="layui-upload-file sku1">
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">Sku描述</label>
                        <div class="layui-input-block">
                            <input required type="text" name="skus[new1][description]" value="{{ old('skus.new1.description') ?? $product->sku1->description ?? '' }}" autocomplete="off" placeholder="Sku描述" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">Sku单价</label>
                        <div class="layui-input-block">
                            <input required type="text" name="skus[new1][price]" value="{{ old('skus.new1.price') ?? $product->sku1->price ?? ''  }}" autocomplete="off" placeholder="Sku单价" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">Sku库存</label>
                        <div class="layui-input-block">
                            <input required type="text" name="skus[new1][stock]" value="{{ old('skus.new1.stock') ?? $product->sku1->stock ?? '' }}" autocomplete="off" placeholder="Sku库存" class="layui-input">
                        </div>
                    </div>


                    <fieldset class="layui-elem-field layui-field-title" style="margin-top: 50px;">
                        <legend>SKU2</legend>
                    </fieldset>
                    <div class="layui-form-item">
                        <label class="layui-form-label">Sku名称</label>
                        <div class="layui-input-block">
                            <input type="text" name="skus[new2][name]" value="{{ old('skus.new2.name') ?? $product->sku2->name ?? ''  }}" autocomplete="off" placeholder="Sku名称" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <div class="layui-form-item">
                            <img id="product_img" style="max-width: 400px; max-height: 600px" src="{{ old('skus.new2.skuImg') ?? $product->sku2->image->src ?? '' }}" alt="">
                            <input required type="hidden" id="product" name="skus[new2][skuImg]" value="{{ old('skus.new2.skuImg') ?? $product->sku2->image->src ?? '' }}">
                        </div>
                        <input type="file" name="file" class="layui-upload-file sku2">
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">Sku描述</label>
                        <div class="layui-input-block">
                            <input type="text" name="skus[new2][description]" value="{{ old('skus.new2.description') ?? $product->sku2->description ?? '' }}" autocomplete="off" placeholder="Sku描述" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">Sku单价</label>
                        <div class="layui-input-block">
                            <input type="text" name="skus[new2][price]" value="{{ old('skus.new2.price') ?? $product->sku2->price ?? '' }}" autocomplete="off" placeholder="Sku单价" class="layui-input">
                        </div>
                    </div>
                    <div class="layui-form-item">
                        <label class="layui-form-label">Sku库存</label>
                        <div class="layui-input-block">
                            <input type="text" name="skus[new2][stock]" value="{{ old('skus.new2.stock') ?? $product->sku2->stock ?? '' }}" autocomplete="off" placeholder="Sku库存" class="layui-input">
                        </div>
                    </div>
                <div class="layui-form-item">
                    <button class="layui-btn"  type="submit">提交</button>
                </div>
            </form>
        </div>
    </body>
        @stop

        @section('script')
            <script>
                window.onload=function () {
                    layui.use(['form','layer','upload'], function(){
                        $ = layui.jquery;
                        var form = layui.form()
                            ,layer = layui.layer;

                        layui.upload({
                            url: '{{ route('admin.product.upload') }}' //接口url
                            ,ext: 'jpg|png|gif' //那么，就只会支持这三种格式的上传。注意是用|分割。
                            ,success: function(res,elem,a){
                                if( res.code != 0) {
                                    layer.msg(res.msg, {icon: 5});
                                    return;
                                }
                                var src = res.data.src;
                                setImg(elem.className,src)
                            }
                            ,error: function (error) {
                                consloe.load('系统异常');
                            }
                        });
                    });
                    layui.use('layedit', function(){
                        var layedit = layui.layedit;

                        layedit.set({
                            uploadImage: {
                                url: '{{ route('admin.product.upload') }}' //接口url
                            }
                        });
                        layedit.build('demo',{
                            height: 500 //设置编辑器高度
                        }); //建立编辑器

                    });

                    function setImg(className,src){
                        className = className.replace('layui-upload-file ','');
                        $(`.${className}`).parent().parent().parent().find('#product').val(src);
                        $(`.${className}`).parent().parent().parent().find('#product_img').attr('src',src);
                    }

                    $('img').on('click',function () {
                        layer.open({
                            type: 1,
                            title: false,
                            closeBtn: 0,
                            area: '516px',
                            skin: 'layui-layer-nobg', //没有背景色
                            shadeClose: true,
                            content: `<img style="max-width: 100%; max-height: 100%" src="${$(this).attr('src')}" alt="">`
                        });
                    })
                }

            </script>


        @stop