routes/web.php
<?php

/**
 * 登录
 * 注册
 * 找回密码
 * 修改密码
 * ---
 * 相关路由
 * 登录状态下跳转到首页
 */




Route::group(['middleware'=>['web','actived']],function (){

    Route::get('/','IndexController@index')->name('index');

    Route::middleware(['guest'])->group(function (){

        # 登陆模块
        Route::get('/login','Auth\LoginController@login')->name('login');
        Route::post('/login','Auth\LoginController@store')->name('login.store');
        Route::get('/weibo/login','Auth\LoginWeiboController@login')->name('login.weibo');
        Route::get('/weibo/user','Auth\LoginWeiboController@user')->name('login.weibo.user');

        Route::get('/qq/handler','Auth\LoginQqController@loginToRedirect')->name('login.qq');
        Route::get('/qq/login','Auth\LoginQqController@login')->name('login.handler');

        # 微信登陆模块
        Route::get('/wx/data','Auth\LoginWinxinController@getCodeAndState')->name('wx.data');
        Route::get('/wx/code','Auth\LoginWinxinController@getCode')->name('wx.code');
        Route::get('/wx/store','Auth\LoginWinxinController@loginStore')->name('wx.store');
        Route::post('/wx/read','Auth\LoginWinxinController@readWxInfo')->name('wx.read');
        Route::get('/wx/login','Auth\LoginWinxinController@login')->name('wx.login');

        /**
         * 忘记密码
         */
        Route::get('/forget','Auth\ForgetController@forget')->name('forget');
        # 获取第一步验证码
        Route::post('/forget/account','Auth\ForgetController@account')->name('forget.account');
        # 第二步：进入填写密码
        Route::get('/forget_too/{key?}','Auth\ForgetController@forget_too')->name('forget_too');
        # 处理第二步：
        Route::post('/forget/store_pwd','Auth\ForgetController@store_pwd')->name('forget.store_pwd');
        # 处理第一步验证码字段相关
        Route::post('/forget','Auth\ForgetController@store')->name('forget.store');
    });

    # 测试相关模块
    Route::get('/test/sub','TestController@sub')->name('sub');
    Route::get('/test/form','TestController@form')->name('test.form');
    Route::get('/test/store','TestController@store')->name('test.store');
    Route::get('/test/qcode','TestController@qcode')->name('qcode');
    Route::get('/test/show','TestController@show')->name('qcode.show');
    Route::get('/test/qcodeStore','TestController@qcodeStore')->name('qcodeStore');
    /**
     *
     * 注册注销相关
     */
    # 注册
    Route::get('/register','Auth\RegisterController@register')->name('register');
    # 注册处理
    Route::post('/register','Auth\RegisterController@store')->name('register.store');
    # 获取验证码
    Route::post('/register/account','Auth\RegisterController@account')->name('register.account');
    #
    Route::get('/register/verify','Auth\RegisterController@verify')->name('verify');

    Route::post('/logout','Auth\LoginController@logout')->name('logout');

    Route::post('/subscriber','SubscriberController@store')->name('subscriber');






    # 必须登录的情况下使用
    Route::middleware(['auth'])->group(function (){
        # 注销
        Route::post('/logout','Auth\LoginController@logout')->name('logout');

        # 收藏清单
        Route::get('/wish','WishController@list')->name('wish');

        # 删除收藏
        Route::delete('/wish','WishController@delete')->name('wish.delete');
        Route::post('/wish','WishController@add')->name('wish.add');


        # 购物车
        Route::get('/carts','CartController@list')->name('cart');
        Route::delete('/carts','CartController@delete')->name('cart.delete');
        Route::put('/carts','CartController@create')->name('cart.create');


        # 订单信息
        Route::get('/order', 'OrderController@list')->name('order.list');
        Route::get('/order/{id}', 'OrderController@show')->name('order.show');
        Route::post('/order/create', 'OrderController@create')->name('order.create');
        Route::post('/order/refund', 'OrderController@refund')->name('order.refund');


        Route::get('/alipay/return','PayController@alipayReturn')->name('pay.alipay.return'); # 前端回调页面
        Route::get('/alipay/{id}','PayController@payByAlipay')->name('pay.alipay');

        Route::get('/wechat/{id}','PayController@payByWechat')->name('pay.wechat');

        # 个人资料页面
        Route::get('/me', 'MeController@index')->name('me.index');


        # 收货地址
        Route::get('/me/address', 'MeController@address')->name('me.address');
        Route::get('/me/address/add_edit/{id?}', 'MeController@add_edit')->name('me.address.add_edit');
        Route::delete('/me/address/delete', 'MeController@delete')->name('me.address.delete');

        # 处理收货地址
        Route::post('/me/address', 'MeController@create')->name('me.address.create');
        Route::put('/me/address', 'MeController@update')->name('me.address.update');

    });


    Route::post('/alipay/notify','PayController@alipayNotify')->name('pay.alipay.notify'); # 支付宝支付成功服务端回调页面

    Route::post('/wechat/notify','PayController@wechatNotify')->name('pay.wechat.notify'); # 微信支付成功服务端回调页面

    Route::post('/wechat/refund/notify','PayController@wechatRefundNotify')->name('pay.wechat.refund'); # 微信退款服务端回调页面


    /**
     * 杂项
     * 关于公司情况的一些模块
     */
    Route::get('/trems_conditions','About\AboutController@trems_conditions');

    # 分类模块
    Route::get('/category','CategoryController@index')->name('category');
    Route::get('/category/{id}','CategoryController@show')->name('category.show');

    # 商品模块
    Route::get('/product/{id}','ProductController@show')->name('product.show');
    Route::get('/product','ProductController@list')->name('product.list');


    Route::namespace('Admin')->group(function () {
        Route::name('admin.')->prefix('admin')->group(function (){

            // 必须登录状态下才能进入
            Route::group(['middleware' => ['auth.admin']], function () {


                Route::get('/', 'IndexController@index')->name('index');
                // 权限控制路由
                Route::group(['middleware'=>'admin.permission'],function (){
                    Route::get('/welcome', 'IndexController@welcome')->name('welcome');;

                    /**
                     * 角色相关
                     */
                    Route::get('/admins/role/store/{id?}', 'AdminController@roleEditOrAdd')->name('admins.role.edit_or_add');
                    Route::get('/admins/role', 'AdminController@role')->name('admins.role');
                    Route::post('/admins/role/store', 'AdminController@roleStore')->name('admins.role.store');
                    Route::delete('/admins/role','AdminController@roleDelete')->name('admins.role.delete');

                    /**
                     * 权限相关
                     */
                    Route::get('/admins/permission', 'AdminController@permission')->name('admins.permission');
                    Route::get('/admins/permission/store/{id?}', 'AdminController@permissionEditOrAdd')->name('admins.permission.edit_or_add');
                    Route::post('/admins/permission/store', 'AdminController@permissionStore')->name('admins.permission.store');
                    Route::get('/admins/permission', 'AdminController@permission')->name('admins.permission');
                    Route::delete('/admins/permission','AdminController@permissionDelete')->name('admins.permission.delete');


                    /**
                     * 管理员管理
                     */
                    Route::get('/admins', 'AdminController@admins')->name('admins.admins');
                    Route::get('/admins/store/{id?}', 'AdminController@adminsEditOrAdd')->name('admins.edit_or_add');
                    Route::post('/admins/store', 'AdminController@adminsStore')->name('admins.store');
                    Route::get('/admins', 'AdminController@admins')->name('admins');
                    Route::delete('/admins','AdminController@adminsDelete')->name('admins.delete');
                    Route::put('/admins/active','AdminController@adminsActived')->name('admins.active');

                    /**
                     * 用户管理
                     */
                    Route::get('/users', 'UserController@list')->name('admins.users');
                    Route::get('/users/store/{id?}', 'UserController@addOrEdit')->name('user.add_or_edit');
                    Route::put('/users/store/{id}', 'UserController@update')->name('user.update');
                    Route::post('/users/store', 'UserController@create')->name('user.create');
                    Route::delete('/users','UserController@delete')->name('user.delete');

                    /**
                     * 分类管理
                     */
                    Route::get('/category', 'CategoryController@list')->name('category');
                    Route::get('/category/store/{id?}', 'CategoryController@addOrEdit')->name('category.add_or_edit');
                    Route::put('/category/store', 'CategoryController@update')->name('category.update');
                    Route::post('/category/store', 'CategoryController@create')->name('category.create');
                    Route::delete('/category','CategoryController@delete')->name('category.delete');

                    /**
                     * 商品管理
                     */
                    Route::get('/product', 'ProductController@list')->name('product');
                    Route::get('/product/store/{id?}', 'ProductController@addOrEdit')->name('product.add_or_edit');
                    Route::put('/product/store', 'ProductController@update')->name('product.update');
                    Route::post('/product/store', 'ProductController@create')->name('product.create');
                    Route::delete('/product','ProductController@delete')->name('product.delete');
                    Route::post('/upload/product','ProductController@upload')->name('product.upload');

                    /**
                     * 首页头图管理
                     */
                    Route::get('/banner', 'BannerController@list')->name('banner');
                    Route::get('/banner/store/{id?}', 'BannerController@add')->name('banner.add');

app/Models/Admin.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class Admin extends Authenticatable
{
    use HasRoles;

    use Notifiable;

    protected $fillable = [
        'name' , 'password', 'salt','actived','avatar'
    ];

    public $guard_name  = 'admin';

    protected $hidden = [
        'password' , 'remember_token','salt'
    ];

    const total = 5;
    /**
     * 获取所有用户
     * @param $bol boolean 是否正序
     */
    public static function getByUserAll($page=true,$timeData=[])
    {
        $type = true ? 'DESC' : 'ASC';
        if( empty($timeData) ) {
            if( $page ) {
                $users = self::getPageUser(self::total);
            }else{
                $users = self::getAllUser();
            }
        }else{
            $users = self::getTimeUserAll($timeData);
        }

        return $users;
    }

    /**
     * 获取所有的权限
     */
    public static function getPermissionAll()
    {
        return \DB::table('permissions')->where('guard_name','admin')->get();
    }

    /**
     *
     * @param $total
     * @return mixed
     */
    public static function getPageUser($total)
    {
        return self::orderBy('created_at','DESC')->paginate($total);
    }


    public static function getAllUser()
    {
        return self::orderBy('created_at','DESC')->get();
    }

    public static function getTimeUserAll($timeData)
    {

    }

    public function getPhoneAttribute($value)
    {
        if( !$value ) {
            return '未设置';
        }
        return $value;
    }

    public function getEmailAttribute($value)
    {
        if( !$value ) {
            return '未设置';
        }
        return $value;
    }

    public function getSimpleRolesAttribute()
    {
        $roles = $this->getRoleNames();
        return $roles;
    }

}

resources/views/admin/admins/list.blade.php
@extends('admin.common.layout')
@section('body')
    <div class="x-nav">
            <span class="layui-breadcrumb">
              <a><cite>首页</cite></a>
              <a><cite>会员管理</cite></a>
              <a><cite>管理员列表</cite></a>
            </span>
        <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right"  href="javascript:location.replace(location.href);" title="刷新"><i class="layui-icon" style="line-height:30px">ဂ</i></a>
    </div>
    <div class="x-body">
        <xblock><button class="layui-btn" onclick="admin_add('添加用户','{{ route('admin.admins.edit_or_add') }}','800','500')">
                <i class="layui-icon">&#xe608;</i>添加</button><span class="x-right" style="line-height:40px">共有数据：{{ $users->count() }} 条</span></xblock>
        <table class="layui-table">
            <thead>
            <tr>
                <th>
                    ID
                </th>
                <th>
                    登录名
                </th>
                <th>
                    手机
                </th>
                <th>
                    邮箱
                </th>
                <th>
                    角色
                </th>
                <th>
                    加入时间
                </th>
                <th>
                    状态
                </th>
                <th>
                    操作
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                @if($user->name != config('main.admin'))
                <tr>
                    <td>
                        {{ $user->id }}
                    </td>
                    <td>
                        {{ $user->name }}
                    </td>
                    <td >
                        {{ $user->phone }}
                    </td>
                    <td >
                        {{ $user->email }}
                    </td>
                    <td >
                        @foreach($user->roles as $role)
                         <span class="layui-btn layui-btn-normal layui-btn-mini">
                                {{ $role->name }}
                            </span>
                        @endforeach
                    </td>
                    <td>
                        {{ $user->created_at }}
                    </td>
                    <td class="td-status">
                        @if($user->actived)
                            <span class="layui-btn layui-btn-normal layui-btn-mini">
                                已启用
                            </span>
                        @else
                            <span class="layui-btn layui-btn-disabled layui-btn-mini">
                                已停用
                            </span>
                        @endif
                    </td>
                    <td class="td-manage">
                        @if($user->actived)
                            <a style="text-decoration:none" onclick="admin_stop(this,'{{ $user->id }}','0')" href="javascript:;" title="停用">
                                <i class="layui-icon">&#xe601;</i>
                            </a>
                        @else
                            <a style="text-decoration:none" onClick="admin_start(this,'{{ $user->id }}','1')" href="javascript:;" title="启用"><i class="layui-icon">&#xe62f;</i></a>
                        @endif

                        <a title="编辑" href="javascript:;" onclick="admin_edit('编辑','{{{ route('admin.admins.edit_or_add',['id' => $user->id]) }}}','4','','510')"
                           class="ml-5" style="text-decoration:none">
                            <i class="layui-icon">&#xe642;</i>
                        </a>
                        <a title="删除" href="javascript:;" onclick="admin_del(this,'{{ $user->id }}')"
                           style="text-decoration:none">
                            <i class="layui-icon">&#xe640;</i>
                        </a>
                    </td>
                </tr>
                @endif
            @endforeach

            </tbody>
        </table>
        @include('admin.common._page',['datas'=>$users , 'datasAll' => $usersAll])
    </div>
@stop

@section('script')
    <script>

        var result = 0;
        layui.use(['element','layer'], function(){
            $ = layui.jquery;//jquery
            laydate = layui.laydate;//日期插件
            lement = layui.element();//面包导航
            layer = layui.layer;//弹出层

            //以上模块根据需要引入

        });

        /*添加*/
        function admin_add(title,url,w,h){
            x_admin_show(title,url,w,h);
        }

        /*停用*/
        function admin_stop(obj,id,actived){
            layer.confirm('确认要停用吗？',function(index){
                if( !parseInt(admin_active(id,actived)) ){
                    return ;
                }
                //发异步把用户状态进行更改
                $(obj).parents("tr").find(".td-manage").prepend(`<a style="text-decoration:none" onClick="admin_start(this,${id},\'1\')" href="javascript:;" title="启用"><i class="layui-icon">&#xe62f;</i></a>`);
                $(obj).parents("tr").find(".td-status").html('<span class="layui-btn layui-btn-disabled layui-btn-mini">已停用</span>');
                $(obj).remove();
                layer.msg('已停用!',{icon: 5,time:1000});
            });
        }

        /*启用*/
        function admin_start(obj,id,actived){
            layer.confirm('确认要启用吗？',function(index){
                //发异步把用户状态进行更改
                if( !parseInt(admin_active(id,actived)) ){
                    return ;
                }
                $(obj).parents("tr").find(".td-manage").prepend(`<a style="text-decoration:none" onClick="admin_stop(this,${id},\'0\')" href="javascript:;" title="停用"><i class="layui-icon">&#xe601;</i></a>`);
                $(obj).parents("tr").find(".td-status").html('<span class="layui-btn layui-btn-normal layui-btn-mini">已启用</span>');
                $(obj).remove();
                layer.msg('已启用!',{icon: 6,time:1000});
            });
        }
        //编辑
        function admin_edit (title,url,id,w,h) {
            x_admin_show(title,url,w,h);
        }
        /*删除*/
        function admin_del(obj,id) {
            layer.confirm('确认要删除吗？', function (index) {
                //发异步删除数据
                $.ajax({
                    type: 'delete',
                    url: '{{ route('admin.admins.delete') }}',
                    dataType: 'json',
                    data: {
                        _method: 'delete',
                        id: id,

                    },
                    success: function (data, text, response) {
                        if (response.status == 200) {
                            $(obj).parents("tr").remove();
                            layer.msg('已删除!', {icon: 1, time: 1000});
                        } else {
                            layer.msg('系统错误!', {icon: 1, time: 1000});
                        }
                    },
                    error: function (error) {
                        if (error.status == 403) {
                            layer.msg('权限不足!', {icon: 1, time: 1000});
                        }
                        layer.msg('系统错误!', {icon: 1, time: 1000});
                    }
                });

            });
        }

        function admin_active(id,active) {
            //发异步删除数据
            $.ajax({
                type: 'put',
                url: '{{ route('admin.admins.active') }}',
                dataType: 'json',
                async: false,
                data: {
                    _method: 'put',
                    id: id,
                    active: active

                },
                success: function (data, text, response) {
                    if (response.status == 200) {
                        // layer.msg('已修改!', {icon: 1, time: 1000});
                        result= 1;
                        console.log(result);
                    } else {
                        layer.msg('系统错误!', {icon: 1, time: 1000});
                        result = 0;
                    }
                },
                error: function (error) {
                    if (error.status == 403) {
                        layer.msg('权限不足!', {icon: 1, time: 1000});
                    }else{
                        layer.msg('系统错误!', {icon: 1, time: 1000});
                    }
                    result = 0;

                }
            });

            console.log(result);
            return result;
        }
    </script>
@stop

resources/views/admin/admins/permission.blade.php
@extends('admin.common.layout')
@section('body')
    <body>
        <div class="x-nav">
            <span class="layui-breadcrumb">
              <a><cite>首页</cite></a>
              <a><cite>会员管理</cite></a>
              <a><cite>权限管理</cite></a>
            </span>
            <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right"  href="javascript:location.replace(location.href);" title="刷新"><i class="layui-icon" style="line-height:30px">ဂ</i></a>
        </div>
        <div class="x-body">
            
            <xblock><button class="layui-btn" onclick="role_add('添加权限','{{ route('admin.admins.permission.edit_or_add') }}','900','500')">
                    <i class="layui-icon">&#xe608;</i>添加</button><span class="x-right" style="line-height:40px">共有数据: {{ $permissions->count() }} 条</span></xblock>
            <table class="layui-table">
                <thead>
                    <tr>
                        <th>
                            ID
                        </th>
                        <th>
                            权限名
                        </th>
                        <th>
                            规则
                        </th>
                        <th>
                            描述
                        </th>
                        <th>
                            创建时间
                        </th>
                        <th>
                            操作
                        </th>
                    </tr>
                </thead>
                <tbody>
                   @foreach($permissions as $permission)
                       <tr>
                           <td>
                               {{ $loop->index + 1}}
                           </td>
                           <td>
                               {{ $permission->name }}
                           </td>
                           <td>
                               {{ $permission->route ?? ''}}
                           </td>
                           <td >
                               {{ $permission->description }}
                           </td>
                           <td >
                               {{ $permission->created_at ?? '' }}
                           </td>
                           <td class="td-manage">
                               <a title="编辑" href="javascript:;" onclick="role_edit('编辑','{{ route('admin.admins.permission.edit_or_add',['id' => $permission->id]) }}','4','','510')"
                                  class="ml-5" style="text-decoration:none">
                                   <i class="layui-icon">&#xe642;</i>
                               </a>
                               <a title="删除" href="javascript:;" onclick="role_del(this,'{{ $permission->id }}')"
                                  style="text-decoration:none">
                                   <i class="layui-icon">&#xe640;</i>
                               </a>
                           </td>
                       </tr>
                   @endforeach
                </tbody>
            </table>

            <div id="page"></div>
        </div>
    </body>
@stop

@section('script')
    <script>
        layui.use(['laydate','element','laypage','layer'], function(){
            $ = layui.jquery;//jquery
            laydate = layui.laydate;//日期插件
            lement = layui.element();//面包导航
            laypage = layui.laypage;//分页
            layer = layui.layer;//弹出层

            //以上模块根据需要引入
        });


        /*添加*/
        function role_add(title,url,w,h){
            x_admin_show(title,url,w,h);
        }


        //编辑
        function role_edit (title,url,id,w,h) {
            x_admin_show(title,url,w,h);
        }

        /*删除*/
        function role_del(obj,id){
            layer.confirm('确认要删除吗？',function(index){
                //发异步删除数据
                $.ajax({
                    type: 'delete',
                    url: '{{ route('admin.admins.permission.delete') }}',
                    dataType: 'json',
                    data: {
                        _method: 'delete',
                        id : id,

                    },
                    success: function (data,text,response) {
                        if( response.status == 200 ){
                            $(obj).parents("tr").remove();
                            layer.msg('已删除!',{icon:1,time:1000});
                        }else{
                            layer.msg('系统错误2!',{icon:1,time:1000});
                        }
                    },
                    error: function (error) {
                        if( error.status == 403 ){
                            layer.msg('权限不够!',{icon:1,time:1000});
                        }
                        layer.msg('系统错误!',{icon:1,time:1000});
                    }
                });

            });
        }
    </script>
@stop

resources/views/admin/admins/role.blade.php
@extends('admin.common.layout')
@section('body')
        <div class="x-nav">
            <span class="layui-breadcrumb">
              <a><cite>首页</cite></a>
              <a><cite>会员管理</cite></a>
              <a><cite>角色管理</cite></a>
            </span>
            <a class="layui-btn layui-btn-small" style="line-height:1.6em;margin-top:3px;float:right"  href="javascript:location.replace(location.href);" title="刷新"><i class="layui-icon" style="line-height:30px">ဂ</i></a>
        </div>
        <div class="x-body">


            <xblock><button class="layui-btn"
                            onclick="role_add('添加用户','{{ route('admin.admins.role.edit_or_add') }}','900','500')">
                    <i class="layui-icon">&#xe608;</i>添加</button><span class="x-right" style="line-height:40px">共有数据：{{ $roles->count() }} 条</span></xblock>
            <table class="layui-table">
                <thead>
                    <tr>
                        <th>
                            Id
                        </th>
                        <th>
                            角色名字
                        </th>
                        <th>
                            角色内容
                        </th>
                        <th>
                            描述
                        </th>
                        <th>
                            操作
                        </th>
                    </tr>
                </thead>
                <tbody>
                @foreach($roles as $role)
                    <tr>
                        <td>
                            {{ $loop->index + 1 }}
                        </td>
                        <td>
                            {{ $role->name }}
                        </td>
                        <td >
                            @foreach($role->permissions as $permission)
                                <button class="layui-btn layui-btn-mini layui-btn-radius layui-btn-normal" onclick="">{{ $permission->name }}</button>
                            @endforeach()
                        </td>
                        <td >
                            {{ $role->description }}
                        </td>
                        <td class="td-manage">
                            <a title="编辑" href="javascript:;" onclick="role_edit('编辑','{{ route('admin.admins.role.edit_or_add',['id'=>$role->id]) }}','4','','510')"
                            class="ml-5" style="text-decoration:none">
                                <i class="layui-icon">&#xe642;</i>
                            </a>
                            <a title="删除" href="javascript:;" onclick="role_del(this,'{{ $role->id }}')"
                            style="text-decoration:none">
                                <i class="layui-icon">&#xe640;</i>
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

            <div id="page"></div>
        </div>
    @stop
@section('script')
    <script>
        layui.use(['laydate','element','laypage','layer'], function(){
            $ = layui.jquery;//jquery
            laydate = layui.laydate;//日期插件
            lement = layui.element();//面包导航
            laypage = layui.laypage;//分页
            layer = layui.layer;//弹出层

            //以上模块根据需要引入
        });


        /*添加*/
        function role_add(title,url,w,h){
            x_admin_show(title,url,w,h);
        }


        //编辑
        function role_edit (title,url,id,w,h) {
            x_admin_show(title,url,w,h);
        }

        /*删除*/
        function role_del(obj,id){
            layer.confirm('确认要删除吗？',function(index){
                //发异步删除数据
                $.ajax({
                    type: 'delete',
                    url: '{{ route('admin.admins.role.delete') }}',
                    dataType: 'json',
                    data: {
                        _method: 'delete',
                        id : id,

                    },
                    success: function (data,text,response) {
                         if( response.status == 200 ){
                             $(obj).parents("tr").remove();
                             layer.msg('已删除!',{icon:1,time:1000});
                         }else{
                             layer.msg('系统错误!',{icon:1,time:1000});
                         }
                    },
                    error: function (error) {
                        if( error.status == 403 ){
                            layer.msg('权限不够!',{icon:1,time:1000});
                        }
                        layer.msg('系统错误!',{icon:1,time:1000});
                    }
                });

            });
        }
    </script>
@stop