routes/web.php
<?php

/**
 * 登录
 * 注册
 * 找回密码
 * 修改密码
 * ---
 * 相关路由
 * 登录状态下跳转到首页
 */




Route::group(['middleware'=>['web','actived']],function (){

    Route::get('/','IndexController@index')->name('index');

    Route::middleware(['guest'])->group(function (){

        # 登陆模块
        Route::get('/login','Auth\LoginController@login')->name('login');
        Route::post('/login','Auth\LoginController@store')->name('login.store');
        Route::get('/weibo/login','Auth\LoginWeiboController@login')->name('login.weibo');
        Route::get('/weibo/user','Auth\LoginWeiboController@user')->name('login.weibo.user');

        Route::get('/qq/handler','Auth\LoginQqController@loginToRedirect')->name('login.qq');
        Route::get('/qq/login','Auth\LoginQqController@login')->name('login.handler');

        # 微信登陆模块
        Route::get('/wx/data','Auth\LoginWinxinController@getCodeAndState')->name('wx.data');
        Route::get('/wx/code','Auth\LoginWinxinController@getCode')->name('wx.code');
        Route::get('/wx/store','Auth\LoginWinxinController@loginStore')->name('wx.store');
        Route::post('/wx/read','Auth\LoginWinxinController@readWxInfo')->name('wx.read');
        Route::get('/wx/login','Auth\LoginWinxinController@login')->name('wx.login');

        /**
         * 忘记密码
         */
        Route::get('/forget','Auth\ForgetController@forget')->name('forget');
        # 获取第一步验证码
        Route::post('/forget/account','Auth\ForgetController@account')->name('forget.account');
        # 第二步：进入填写密码
        Route::get('/forget_too/{key?}','Auth\ForgetController@forget_too')->name('forget_too');
        # 处理第二步：
        Route::post('/forget/store_pwd','Auth\ForgetController@store_pwd')->name('forget.store_pwd');
        # 处理第一步验证码字段相关
        Route::post('/forget','Auth\ForgetController@store')->name('forget.store');
    });

    # 测试相关模块
    Route::get('/test/sub','TestController@sub')->name('sub');
    Route::get('/test/form','TestController@form')->name('test.form');
    Route::get('/test/store','TestController@store')->name('test.store');
    Route::get('/test/qcode','TestController@qcode')->name('qcode');
    Route::get('/test/show','TestController@show')->name('qcode.show');
    Route::get('/test/qcodeStore','TestController@qcodeStore')->name('qcodeStore');
    /**
     *
     * 注册注销相关
     */
    # 注册
    Route::get('/register','Auth\RegisterController@register')->name('register');
    # 注册处理
    Route::post('/register','Auth\RegisterController@store')->name('register.store');
    # 获取验证码
    Route::post('/register/account','Auth\RegisterController@account')->name('register.account');
    #
    Route::get('/register/verify','Auth\RegisterController@verify')->name('verify');

    Route::post('/logout','Auth\LoginController@logout')->name('logout');

    Route::post('/subscriber','SubscriberController@store')->name('subscriber');






    # 必须登录的情况下使用
    Route::middleware(['auth'])->group(function (){
        # 注销
        Route::post('/logout','Auth\LoginController@logout')->name('logout');

        # 收藏清单
        Route::get('/wish','WishController@list')->name('wish');

        # 删除收藏
        Route::delete('/wish','WishController@delete')->name('wish.delete');
        Route::post('/wish','WishController@add')->name('wish.add');


        # 购物车
        Route::get('/carts','CartController@list')->name('cart');
        Route::delete('/carts','CartController@delete')->name('cart.delete');
        Route::put('/carts','CartController@create')->name('cart.create');


        # 订单信息
        Route::get('/order', 'OrderController@list')->name('order.list');
        Route::get('/order/{id}', 'OrderController@show')->name('order.show');
        Route::post('/order/create', 'OrderController@create')->name('order.create');
        Route::post('/order/refund', 'OrderController@refund')->name('order.refund');


        Route::get('/alipay/return','PayController@alipayReturn')->name('pay.alipay.return'); # 前端回调页面
        Route::get('/alipay/{id}','PayController@payByAlipay')->name('pay.alipay');

        Route::get('/wechat/{id}','PayController@payByWechat')->name('pay.wechat');

        # 个人资料页面
        Route::get('/me', 'MeController@index')->name('me.index');


        # 收货地址
        Route::get('/me/address', 'MeController@address')->name('me.address');
        Route::get('/me/address/add_edit/{id?}', 'MeController@add_edit')->name('me.address.add_edit');
        Route::delete('/me/address/delete', 'MeController@delete')->name('me.address.delete');

        # 处理收货地址
        Route::post('/me/address', 'MeController@create')->name('me.address.create');
        Route::put('/me/address', 'MeController@update')->name('me.address.update');

    });


    Route::post('/alipay/notify','PayController@alipayNotify')->name('pay.alipay.notify'); # 支付宝支付成功服务端回调页面

    Route::post('/wechat/notify','PayController@wechatNotify')->name('pay.wechat.notify'); # 微信支付成功服务端回调页面

    Route::post('/wechat/refund/notify','PayController@wechatRefundNotify')->name('pay.wechat.refund'); # 微信退款服务端回调页面


    /**
     * 杂项
     * 关于公司情况的一些模块
     */
    Route::get('/trems_conditions','About\AboutController@trems_conditions');

    # 分类模块
    Route::get('/category','CategoryController@index')->name('category');
    Route::get('/category/{id}','CategoryController@show')->name('category.show');

    # 商品模块
    Route::get('/product/{id}','ProductController@show')->name('product.show');
    Route::get('/product','ProductController@list')->name('product.list');


    Route::namespace('Admin')->group(function () {
        Route::name('admin.')->prefix('admin')->group(function (){

            // 必须登录状态下才能进入
            Route::group(['middleware' => ['auth.admin']], function () {


                Route::get('/', 'IndexController@index')->name('index');
                // 权限控制路由
                Route::group(['middleware'=>'admin.permission'],function (){
                    Route::get('/welcome', 'IndexController@welcome')->name('welcome');;

                    /**
                     * 角色相关
                     */
                    Route::get('/admins/role/store/{id?}', 'AdminController@roleEditOrAdd')->name('admins.role.edit_or_add');
                    Route::get('/admins/role', 'AdminController@role')->name('admins.role');
                    Route::post('/admins/role/store', 'AdminController@roleStore')->name('admins.role.store');
                    Route::delete('/admins/role','AdminController@roleDelete')->name('admins.role.delete');

                    /**
                     * 权限相关
                     */
                    Route::get('/admins/permission', 'AdminController@permission')->name('admins.permission');
                    Route::get('/admins/permission/store/{id?}', 'AdminController@permissionEditOrAdd')->name('admins.permission.edit_or_add');
                    Route::post('/admins/permission/store', 'AdminController@permissionStore')->name('admins.permission.store');
                    Route::get('/admins/permission', 'AdminController@permission')->name('admins.permission');
                    Route::delete('/admins/permission','AdminController@permissionDelete')->name('admins.permission.delete');


                    /**
                     * 管理员管理
                     */
                    Route::get('/admins', 'AdminController@admins')->name('admins.admins');
                    Route::get('/admins/store/{id?}', 'AdminController@adminsEditOrAdd')->name('admins.edit_or_add');
                    Route::post('/admins/store', 'AdminController@adminsStore')->name('admins.store');
                    Route::get('/admins', 'AdminController@admins')->name('admins');
                    Route::delete('/admins','AdminController@adminsDelete')->name('admins.delete');
                    Route::put('/admins/active','AdminController@adminsActived')->name('admins.active');

                    /**
                     * 用户管理
                     */
                    Route::get('/users', 'UserController@list')->name('admins.users');
                    Route::get('/users/store/{id?}', 'UserController@addOrEdit')->name('user.add_or_edit');
                    Route::put('/users/store/{id}', 'UserController@update')->name('user.update');
                    Route::post('/users/store', 'UserController@create')->name('user.create');
                    Route::delete('/users','UserController@delete')->name('user.delete');

                    /**
                     * 分类管理
                     */
                    Route::get('/category', 'CategoryController@list')->name('category');
                    Route::get('/category/store/{id?}', 'CategoryController@addOrEdit')->name('category.add_or_edit');
                    Route::put('/category/store', 'CategoryController@update')->name('category.update');
                    Route::post('/category/store', 'CategoryController@create')->name('category.create');
                    Route::delete('/category','CategoryController@delete')->name('category.delete');

                    /**
                     * 商品管理
                     */
                    Route::get('/product', 'ProductController@list')->name('product');
                    Route::get('/product/store/{id?}', 'ProductController@addOrEdit')->name('product.add_or_edit');
                    Route::put('/product/store', 'ProductController@update')->name('product.update');
                    Route::post('/product/store', 'ProductController@create')->name('product.create');
                    Route::delete('/product','ProductController@delete')->name('product.delete');
                    Route::post('/upload/product','ProductController@upload')->name('product.upload');

                    /**
                     * 首页头图管理
                     */
                    Route::get('/banner', 'BannerController@list')->name('banner');
                    Route::get('/banner/store/{id?}', 'BannerController@add')->name('banner.add');

app/Models/Cart.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use App\Http\Traits\CartCacheTrait;

class Cart extends BaseModel
{

    use CartCacheTrait;

    const key = 'cart';

    protected $guarded = [];

    public function productSku()
    {
        return $this->belongsTo(ProductSku::class,'product_sku_id','id');
    }

    public static function getCartByProductSku()
    {
        $user = Auth::user();

        $products = collect([]);

        $carts = self::with(['productSku','productSku.image','productSku.product.category'])->where('user_id',$user->id)->get();

        return $carts;
    }

    public static function getCartByUser($id) {
        $carts =  self::getCacheCart($id);
        return $carts;
    }


    public function getImageAttribute()
    {
        return $this->productSku->image->src;
    }

    public function getNameAttribute()
    {
        return $this->productSku->name;
    }

    public function getCnameAttribute()
    {
        return $this->productSku->product->category->name;
    }

    public function getPriceAttribute()
    {
        return $this->productSku->price;
    }

    public function getTotalPriceAttribute()
    {
        $total = $this->price * $this->amount;
        return sprintf('%.2f',$total);
    }

    public static function remove($pid)
    {
        $uid = Auth::id();

        if( $simple = self::where('id',$pid)->orWhere('user_id',$uid)->first() ){
            $simple->delete();
            return true;
        }

        return false;
    }
}

app/Models/Category.php
<?php

namespace App\Models;

use App\Http\Traits\CategoryCacheTrait;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends BaseModel
{
    use CategoryCacheTrait;

    use SoftDeletes;

    const key = 'category';

    public static function getCategoryAll($bol=true)
    {
        $categories = self::getCacheCategory();
        return $categories;
    }

    /**
     * 首页获取分类数量
     * @param int $len
     * @return \Illuminate\Database\Eloquent\Builder[]|\Illuminate\Database\Eloquent\Collection
     */
    public static function getByCategory($len=9)
    {
        $categories = self::getCacheCategory()->take($len);
        return $categories;
    }


    public function product()
    {
        return $this->hasMany(Product::class,'category_id','id');
    }


    public function getPcountAttribute()
    {
        return $this->product->count();
    }
}

resources/views/index/index.blade.php
@extends('layout.layout')
@section('title','首页')
@section('main')
    <main id="mainContent" class="main-content">
        <div class="page-container ptb-10">
            <div class="container">
                <div class="section deals-header-area ptb-30">
                    <div class="row row-tb-20">
                        <div class="col-xs-12 col-md-4 col-lg-3">
                            <aside>
                                <ul class="nav-coupon-category panel">
                                    @foreach($categories as $category)
                                        @if( $category->pcount > 0 )
                                        <li><a href="{{ route('category.show',['id' => $category->id]) }}"><i class="fa fa-navicon"></i>{{ $category->name }}
                                                <span>{{ $category->pcount }}</span></a>
                                        </li>
                                        @endif
                                    @endforeach
                                    <li class="all-cat">
                                        <a class="font-14" href="{{ route('category') }}">查看所有分类</a>
                                    </li>
                                </ul>
                            </aside>
                        </div>
                        <div class="col-xs-12 col-md-8 col-lg-9">
                            <div class="header-deals-slider owl-slider" data-loop="true" data-autoplay="true"
                                 data-autoplay-timeout="10000" data-smart-speed="1000" data-nav-speed="false"
                                 data-nav="true" data-xxs-items="1" data-xxs-nav="true" data-xs-items="1"
                                 data-xs-nav="true" data-sm-items="1" data-sm-nav="true" data-md-items="1"
                                 data-md-nav="true" data-lg-items="1" data-lg-nav="true">
                                @foreach($banners as $banner)
                                <div class="deal-single panel item">
                                    <figure class="deal-thumbnail embed-responsive embed-responsive-16by9"
                                            data-bg-img="{{ $banner->product->image_src }}">
                                        <div class="label-discount top-10 right-10">{{ $banner->product->cname }}</div>
                                        <ul class="deal-actions top-10 left-10">
                                            <li class="like-deal" data-id="{{ $banner->product->id }}">
                                                    <span>
			                        <i class="fa fa-heart"></i>
			                    </span>
                                            </li>
                                            <li class="share-btn">
                                                <div class="share-tooltip fade">
                                                    <a target="_blank" href="#"><i class="fa fa-weibo"></i></a>
                                                    <a target="_blank" href="#"><i class="fa fa-qq"></i></a>
                                                    <a target="_blank" href="#"><i class="fa fa-wechat"></i></a>
                                                </div>
                                                <span><i class="fa fa-share-alt"></i></span>
                                            </li>
                                        </ul>
                                        <div class="deal-about p-20 pos-a bottom-0 left-0">
                                            <div class="rating mb-10">
                                                    <span class="rating-stars" data-rating="{{ $banner->product->rating }}">
			                        <i class="fa fa-star-o star-active"></i>
			                        <i class="fa fa-star-o"></i>
			                        <i class="fa fa-star-o"></i>
			                        <i class="fa fa-star-o"></i>
			                        <i class="fa fa-star-o"></i>
			                    </span>
                                                <span class="rating-reviews color-light">
			                    	( <span class="rating-count">{{ $banner->product->review_count }}</span> 条评论 )
                                                    </span>
                                            </div>
                                            <h3 class="deal-title mb-10 ">
                                                <a href="{{ route('product.show',['id'=>$banner->product->id]) }}l" class="color-light color-h-lighter">{{ $banner->product->name }}</a>
                                            </h3>
                                        </div>
                                    </figure>
                                </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>


                <section class="section latest-deals-area ptb-30">
                    <header class="panel ptb-15 prl-20 pos-r mb-30">
                        <h3 class="section-title font-18">最新商品</h3>
                        <a href="{{ route('product.list') }}" class="btn btn-o btn-xs pos-a right-10 pos-tb-center">查看所有</a>
                    </header>

                    <div class="row row-masnory row-tb-20">
                        @foreach($products as $product)
                            <div class="col-sm-6 col-lg-4">
                                <div class="deal-single panel">
                                    <figure class="deal-thumbnail embed-responsive embed-responsive-16by9"
                                            data-bg-img="{{ $product->image_src }}">
                                        <div class="label-discount left-20 top-15">{{ $product->cName }}</div>
                                        <ul class="deal-actions top-15 right-20">
                                            <li class="like-deal" data-id="{{ $product->id }}"><span><i class="fa fa-heart"></i></span>
                                            </li>
                                            <li class="share-btn">
                                                <div class="share-tooltip fade">
                                                    <a target="_blank" href="#"><i class="fa fa-facebook"></i></a>
                                                    <a target="_blank" href="#"><i class="fa fa-twitter"></i></a>
                                                    <a target="_blank" href="#"><i class="fa fa-google-plus"></i></a>
                                                    <a target="_blank" href="#"><i class="fa fa-pinterest"></i></a>
                                                </div>
                                                <span><i class="fa fa-share-alt"></i></span>
                                            </li>
                                        </ul>
                                        <div class="deal-store-logo">
                                            <a href="{{ route('product.show',['id'=>$product->id]) }}"><img src="{{ $product->image_src }}" alt=""></a>
                                        </div>
                                    </figure>
                                    <div class="bg-white pt-20 pl-20 pr-15">
                                        <div class="pr-md-10">
                                            <div class="rating mb-10">
                                                <span class="rating-stars rate-allow"
                                                      data-rating="{{ $product->rating ?? 1 }}">
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                            <i class="fa fa-star-o"></i>
                                        </span>
                                                <span class="rating-reviews">
                                ( <span class="rating-count">{{ $product->review_count }}</span> 评论数 )
                                                </span>
                                            </div>
                                            <h3 class="deal-title mb-10">
                                                <a href="{{ route('product.show',['id'=>$product->id]) }}">{{ $product->name }}</a>
                                            </h3>
                                            <ul class="deal-meta list-inline mb-10 color-mid">
                                                <li>
                                                    <i class="ico mr-10">成交量:</i>{{ $product->sold_count }}
                                                </li>
                                            </ul>
                                        </div>
                                        <div class="deal-price pos-r mb-15">
                                            <h3 class="price ptb-5 text-right">价格：<span
                                                        class="price-sale"></span>{{ $product->price }}</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </section>


                {{--折扣商品 见 about.temp_sale--}}

                {{-- 活跃用户 --}}
                <section class="section stores-area stores-area-v1 ptb-30">
                    <header class="panel ptb-15 prl-20 pos-r mb-30">
                        <h3 class="section-title font-18">活跃用户</h3>
                    </header>
                    <div class="popular-stores-slider owl-slider" data-loop="true" data-autoplay="true"
                         data-smart-speed="1000" data-autoplay-timeout="10000" data-margin="20" data-items="2"
                         data-xxs-items="2" data-xs-items="2" data-sm-items="3" data-md-items="5" data-lg-items="6">

                        @foreach($users as $user)
                        <div class="store-item t-center">
                            <a href="javascript:;" class="panel is-block">
                                <div class="embed-responsive embed-responsive-4by3">
                                    <div class="store-logo">
                                        <img src="{{ $user['avatar'] }}" alt="">
                                    </div>
                                </div>
                                <h6 class="store-name ptb-10">{{ $user['name'] }}</h6>
                            </a>
                        </div>
                        @endforeach

                    </div>
                </section>

                <section class="section subscribe-area ptb-40 t-center">
                    <div class="newsletter-form">
                        <h4 class="mb-20"><i class="fa fa-envelope-o color-green mr-10"></i>订阅我们</h4>
                        <p class="mb-20 color-mid">我们将每天9.00给您发一篇最新的资讯文章或者商品</p>
                            <div class="input-group mb-10">
                                <input type="email" value="{{ \Auth::user()->email ?? '' }}"
                                       class="form-control bg-white" id="sub_email" placeholder="邮箱地址" required="required">
                                <span class="input-group-btn">
                                    <button class="btn" type="button" id="subscribers">订阅我们</button>
                                </span>
                            </div>
                        <p class="color-muted"><small>我们绝不会外泄您的邮箱</small> </p>
                    </div>
                </section>
            </div>
        </div>

    </main>
@stop

@section('script')
    <script>
        $('#subscribers').on('click',function () {
            var email = $('#sub_email').val();
            $.ajax({
                url: '{{ route('subscriber') }}',
                type: 'post',
                data: {
                    email: email
                },
                success: function (data,status,res) {
                    if( res.status == 200 ) {
                        swal('订阅成功，请查看邮箱','','success');
                    }else{
                        swal(data.msg,'','error');
                    }
                },
                error: function (data) {
                    if(typeof data.responseJSON.msg != undefined ) {
                        console.log(data.responseJSON.msg)
                        swal(data.responseJSON.msg,'','error');
                    }else{
                        swal('系统错误','','error');
                    }

                }
            })
        })
    </script>
    @include('layout._extend_js')
@stop