routes/web.php
<?php

/**
 * 登录
 * 注册
 * 找回密码
 * 修改密码
 * ---
 * 相关路由
 * 登录状态下跳转到首页
 */




Route::group(['middleware'=>['web','actived']],function (){

    Route::get('/','IndexController@index')->name('index');

    Route::middleware(['guest'])->group(function (){

        # 登陆模块
        Route::get('/login','Auth\LoginController@login')->name('login');
        Route::post('/login','Auth\LoginController@store')->name('login.store');
        Route::get('/weibo/login','Auth\LoginWeiboController@login')->name('login.weibo');
        Route::get('/weibo/user','Auth\LoginWeiboController@user')->name('login.weibo.user');

        Route::get('/qq/handler','Auth\LoginQqController@loginToRedirect')->name('login.qq');
        Route::get('/qq/login','Auth\LoginQqController@login')->name('login.handler');

        # 微信登陆模块
        Route::get('/wx/data','Auth\LoginWinxinController@getCodeAndState')->name('wx.data');
        Route::get('/wx/code','Auth\LoginWinxinController@getCode')->name('wx.code');
        Route::get('/wx/store','Auth\LoginWinxinController@loginStore')->name('wx.store');
        Route::post('/wx/read','Auth\LoginWinxinController@readWxInfo')->name('wx.read');
        Route::get('/wx/login','Auth\LoginWinxinController@login')->name('wx.login');

        /**
         * 忘记密码
         */
        Route::get('/forget','Auth\ForgetController@forget')->name('forget');
        # 获取第一步验证码
        Route::post('/forget/account','Auth\ForgetController@account')->name('forget.account');
        # 第二步：进入填写密码
        Route::get('/forget_too/{key?}','Auth\ForgetController@forget_too')->name('forget_too');
        # 处理第二步：
        Route::post('/forget/store_pwd','Auth\ForgetController@store_pwd')->name('forget.store_pwd');
        # 处理第一步验证码字段相关
        Route::post('/forget','Auth\ForgetController@store')->name('forget.store');
    });

    # 测试相关模块
    Route::get('/test/sub','TestController@sub')->name('sub');
    Route::get('/test/form','TestController@form')->name('test.form');
    Route::get('/test/store','TestController@store')->name('test.store');
    Route::get('/test/qcode','TestController@qcode')->name('qcode');
    Route::get('/test/show','TestController@show')->name('qcode.show');
    Route::get('/test/qcodeStore','TestController@qcodeStore')->name('qcodeStore');
    /**
     *
     * 注册注销相关
     */
    # 注册
    Route::get('/register','Auth\RegisterController@register')->name('register');
    # 注册处理
    Route::post('/register','Auth\RegisterController@store')->name('register.store');
    # 获取验证码
    Route::post('/register/account','Auth\RegisterController@account')->name('register.account');
    #
    Route::get('/register/verify','Auth\RegisterController@verify')->name('verify');

    Route::post('/logout','Auth\LoginController@logout')->name('logout');

    Route::post('/subscriber','SubscriberController@store')->name('subscriber');






    # 必须登录的情况下使用
    Route::middleware(['auth'])->group(function (){
        # 注销
        Route::post('/logout','Auth\LoginController@logout')->name('logout');

        # 收藏清单
        Route::get('/wish','WishController@list')->name('wish');

        # 删除收藏
        Route::delete('/wish','WishController@delete')->name('wish.delete');
        Route::post('/wish','WishController@add')->name('wish.add');


        # 购物车
        Route::get('/carts','CartController@list')->name('cart');
        Route::delete('/carts','CartController@delete')->name('cart.delete');
        Route::put('/carts','CartController@create')->name('cart.create');


        # 订单信息
        Route::get('/order', 'OrderController@list')->name('order.list');
        Route::get('/order/{id}', 'OrderController@show')->name('order.show');
        Route::post('/order/create', 'OrderController@create')->name('order.create');
        Route::post('/order/refund', 'OrderController@refund')->name('order.refund');


        Route::get('/alipay/return','PayController@alipayReturn')->name('pay.alipay.return'); # 前端回调页面
        Route::get('/alipay/{id}','PayController@payByAlipay')->name('pay.alipay');

        Route::get('/wechat/{id}','PayController@payByWechat')->name('pay.wechat');

        # 个人资料页面
        Route::get('/me', 'MeController@index')->name('me.index');


        # 收货地址
        Route::get('/me/address', 'MeController@address')->name('me.address');
        Route::get('/me/address/add_edit/{id?}', 'MeController@add_edit')->name('me.address.add_edit');
        Route::delete('/me/address/delete', 'MeController@delete')->name('me.address.delete');

        # 处理收货地址
        Route::post('/me/address', 'MeController@create')->name('me.address.create');
        Route::put('/me/address', 'MeController@update')->name('me.address.update');

    });


    Route::post('/alipay/notify','PayController@alipayNotify')->name('pay.alipay.notify'); # 支付宝支付成功服务端回调页面

    Route::post('/wechat/notify','PayController@wechatNotify')->name('pay.wechat.notify'); # 微信支付成功服务端回调页面

    Route::post('/wechat/refund/notify','PayController@wechatRefundNotify')->name('pay.wechat.refund'); # 微信退款服务端回调页面


    /**
     * 杂项
     * 关于公司情况的一些模块
     */
    Route::get('/trems_conditions','About\AboutController@trems_conditions');

    # 分类模块
    Route::get('/category','CategoryController@index')->name('category');
    Route::get('/category/{id}','CategoryController@show')->name('category.show');

    # 商品模块
    Route::get('/product/{id}','ProductController@show')->name('product.show');
    Route::get('/product','ProductController@list')->name('product.list');


    Route::namespace('Admin')->group(function () {
        Route::name('admin.')->prefix('admin')->group(function (){

            // 必须登录状态下才能进入
            Route::group(['middleware' => ['auth.admin']], function () {


                Route::get('/', 'IndexController@index')->name('index');
                // 权限控制路由
                Route::group(['middleware'=>'admin.permission'],function (){
                    Route::get('/welcome', 'IndexController@welcome')->name('welcome');;

                    /**
                     * 角色相关
                     */
                    Route::get('/admins/role/store/{id?}', 'AdminController@roleEditOrAdd')->name('admins.role.edit_or_add');
                    Route::get('/admins/role', 'AdminController@role')->name('admins.role');
                    Route::post('/admins/role/store', 'AdminController@roleStore')->name('admins.role.store');
                    Route::delete('/admins/role','AdminController@roleDelete')->name('admins.role.delete');

                    /**
                     * 权限相关
                     */
                    Route::get('/admins/permission', 'AdminController@permission')->name('admins.permission');
                    Route::get('/admins/permission/store/{id?}', 'AdminController@permissionEditOrAdd')->name('admins.permission.edit_or_add');
                    Route::post('/admins/permission/store', 'AdminController@permissionStore')->name('admins.permission.store');
                    Route::get('/admins/permission', 'AdminController@permission')->name('admins.permission');
                    Route::delete('/admins/permission','AdminController@permissionDelete')->name('admins.permission.delete');


                    /**
                     * 管理员管理
                     */
                    Route::get('/admins', 'AdminController@admins')->name('admins.admins');
                    Route::get('/admins/store/{id?}', 'AdminController@adminsEditOrAdd')->name('admins.edit_or_add');
                    Route::post('/admins/store', 'AdminController@adminsStore')->name('admins.store');
                    Route::get('/admins', 'AdminController@admins')->name('admins');
                    Route::delete('/admins','AdminController@adminsDelete')->name('admins.delete');
                    Route::put('/admins/active','AdminController@adminsActived')->name('admins.active');

                    /**
                     * 用户管理
                     */
                    Route::get('/users', 'UserController@list')->name('admins.users');
                    Route::get('/users/store/{id?}', 'UserController@addOrEdit')->name('user.add_or_edit');
                    Route::put('/users/store/{id}', 'UserController@update')->name('user.update');
                    Route::post('/users/store', 'UserController@create')->name('user.create');
                    Route::delete('/users','UserController@delete')->name('user.delete');

                    /**
                     * 分类管理
                     */
                    Route::get('/category', 'CategoryController@list')->name('category');
                    Route::get('/category/store/{id?}', 'CategoryController@addOrEdit')->name('category.add_or_edit');
                    Route::put('/category/store', 'CategoryController@update')->name('category.update');
                    Route::post('/category/store', 'CategoryController@create')->name('category.create');
                    Route::delete('/category','CategoryController@delete')->name('category.delete');

                    /**
                     * 商品管理
                     */
                    Route::get('/product', 'ProductController@list')->name('product');
                    Route::get('/product/store/{id?}', 'ProductController@addOrEdit')->name('product.add_or_edit');
                    Route::put('/product/store', 'ProductController@update')->name('product.update');
                    Route::post('/product/store', 'ProductController@create')->name('product.create');
                    Route::delete('/product','ProductController@delete')->name('product.delete');
                    Route::post('/upload/product','ProductController@upload')->name('product.upload');

                    /**
                     * 首页头图管理
                     */
                    Route::get('/banner', 'BannerController@list')->name('banner');
                    Route::get('/banner/store/{id?}', 'BannerController@add')->name('banner.add');

resources/views/admin/layout/_header.blade.php
<div class="layui-header header header-demo">
    <div class="layui-main">
        <a class="logo" href="/admin">
            {{ config('main.name') }} - 后台管理
        </a>
        <ul class="layui-nav" lay-filter="">
            <li class="layui-nav-item"><img src="./images/logo.png" class="layui-circle" style="border: 2px solid #A9B7B7;" width="35px" alt=""></li>
            <li class="layui-nav-item">
                <a href="javascript:;">{{ $user->name }}</a>
                <dl class="layui-nav-child"> <!-- 二级菜单 -->
                    <dd><a href="">个人信息</a></dd>
                    <dd><a href="javascript:;" onclick="document.getElementById('logout').submit()">切换帐号</a></dd>
                    <form id="logout" action="{{ route('admin.logout') }}" method="post">
                        {{ csrf_field() }}
                    </form>
                </dl>
            </li>
            <!-- <li class="layui-nav-item">
              <a href="" title="消息">
                  <i class="layui-icon" style="top: 1px;">&#xe63a;</i>
              </a>
              </li> -->
            <li class="layui-nav-item x-index"><a href="/">前台首页</a></li>
        </ul>
    </div>
</div>

resources/views/admin/layout/_menu.blade.php
<div class="layui-side layui-bg-black x-side">
    <div class="layui-side-scroll">
        <ul class="layui-nav layui-nav-tree site-demo-nav" lay-filter="side">
            <li class="layui-nav-item">
                <a class="javascript:;" href="javascript:;">
                    <i class="layui-icon" style="top: 3px;">&#xe62d;</i><cite>产品管理</cite>
                </a>
                <dl class="layui-nav-child">
                    <dd class="">
                        <a href="javascript:;" _href="{{ route('admin.product') }}">
                            <cite>商品管理</cite>
                        </a>
                    </dd>
                </dl>
            </li>
            <li class="layui-nav-item">
                <a class="javascript:;" href="javascript:;">
                    <i class="layui-icon" style="top: 3px;">&#xe634;</i><cite>轮播管理</cite>
                </a>
                <dl class="layui-nav-child">
                    <dd class="">
                        <a href="javascript:;" _href="{{ route('admin.banner') }}">
                            <cite>轮播管理</cite>
                        </a>
                    </dd>
                </dl>
            </li>
            <li class="layui-nav-item">
                <a class="javascript:;" href="javascript:;">
                    <i class="layui-icon" style="top: 3px;">&#xe642;</i><cite>订单管理</cite>
                </a>
                <dl class="layui-nav-child">
                    <dd class="">
                        <a href="javascript:;" _href="{{ route('admin.order') }}">
                            <cite>订单列表</cite>
                        </a>
                    </dd>
                </dl>
            </li>
            <li class="layui-nav-item">
                <a class="javascript:;" href="javascript:;">
                    <i class="layui-icon" style="top: 3px;">&#xe630;</i><cite>分类管理</cite>
                </a>
                <dl class="layui-nav-child">
                    <dd class="">
                        <a href="javascript:;" _href="{{ route('admin.category') }}">
                            <cite>分类列表</cite>
                        </a>
                    </dd>
                </dl>
            </li>
            {{--<li class="layui-nav-item">--}}
                {{--<a class="javascript:;" href="javascript:;">--}}
                    {{--<i class="layui-icon" style="top: 3px;">&#xe606;</i><cite>评论管理</cite>--}}
                {{--</a>--}}
                {{--<dl class="layui-nav-child">--}}
                    {{--<dd class="">--}}
                        {{--<a href="javascript:;" _href="./comment-list.html">--}}
                            {{--<cite>评论列表</cite>--}}
                        {{--</a>--}}
                    {{--</dd>--}}
                    {{--<dd class="">--}}
                        {{--<a href="javascript:;" _href="./feedback-list.html">--}}
                            {{--<cite>意见反馈</cite>--}}
                        {{--</a>--}}
                    {{--</dd>--}}
                {{--</dl>--}}
            {{--</li>--}}
            <li class="layui-nav-item">
                <a class="javascript:;" href="javascript:;">
                    <i class="layui-icon" style="top: 3px;">&#xe612;</i><cite>会员管理</cite>
                </a>
                <dl class="layui-nav-child">
                    <dd class="">
                        <a href="javascript:;" _href="{{ route('admin.admins.users') }}">
                            <cite>会员列表</cite>
                        </a>
                    </dd>
                </dl>
            </li>
            <li class="layui-nav-item">
                <a class="javascript:;" href="javascript:;">
                    <i class="layui-icon" style="top: 3px;">&#xe613;</i><cite>管理员管理</cite>
                </a>
                <dl class="layui-nav-child">
                    <dd class="">
                        <a href="javascript:;" _href="{{ route('admin.admins') }}">
                            <cite>管理员列表</cite>
                        </a>
                    </dd>
                    <dd class="">
                        <a href="javascript:;" _href="{{ route('admin.admins.role') }}">
                            <cite>角色管理</cite>
                        </a>
                    </dd>
                    <dd class="">
                        <a href="javascript:;" _href="{{ route('admin.admins.permission') }}">
                            <cite>权限管理</cite>
                        </a>
                    </dd>
                </dl>
            </li>
        </ul>
    </div>

</div>